# Change these first
owner: nonamenix
repo: uptime

# Add your sites here
sites:
  - name: nonamenix.ru
    url: https://nonamenix.ru
  - name: photopuma.ru
    url: https://photopuma.ru
  - name: worldofwarships.ru
    url: https://worldofwarships.ru
  - name: clans.worldofwarships.ru
    url: https://clans.worldofwarships.ru
  - name: armory.worldofwarships.ru
    url: https://armory.worldofwarships.ru
  - name: dockyard.worldofwarships.ru
    url: https://dockyard.worldofwarships.ru

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.live4.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Uptime"
  introMessage: yet another uptime page in internet. Powerred by [upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
