# Change these first
owner: live4dev
repo: uptime

# Add your sites here
sites:
  - name: nonamenix.ru
    url: https://nonamenix.ru
  - name: live4.dev
    url: https://live4.dev
  - name: cv.live4.dev
    url: https://cv.live4.dev
#  - name: photopuma.ru
#    url: https://photopuma.ru
  - name: worldofwarships.ru
    url: https://worldofwarships.ru
  - name: clans.worldofwarships.ru
    url: https://clans.worldofwarships.ru
  - name: armory.worldofwarships.ru
    url: https://armory.worldofwarships.ru
  - name: dockyard.worldofwarships.ru
    url: https://dockyard.worldofwarships.ru
    expectedStatusCodes:
      - 403
  - name: logbook.worldofwarships.ru
    url: https://logbook.worldofwarships.ru
  - name: worldofwarships.com
    url: https://worldofwarships.com
  - name: clans.worldofwarships.com
    url: https://clans.worldofwarships.com
  - name: armory.worldofwarships.com
    url: https://armory.worldofwarships.com
  - name: dockyard.worldofwarships.com
    url: https://dockyard.worldofwarships.com
    expectedStatusCodes:
      - 403
  - name: logbook.worldofwarships.com
    url: https://logbook.worldofwarships.com
  - name: worldofwarships.eu
    url: https://worldofwarships.eu
  - name: clans.worldofwarships.eu
    url: https://clans.worldofwarships.eu
  - name: armory.worldofwarships.eu
    url: https://armory.worldofwarships.eu
  - name: dockyard.worldofwarships.eu
    url: https://dockyard.worldofwarships.eu
    expectedStatusCodes:
      - 403
  - name: logbook.worldofwarships.eu
    url: https://logbook.worldofwarships.eu
  - name: worldofwarships.asia
    url: https://worldofwarships.asia
  - name: clans.worldofwarships.asia
    url: https://clans.worldofwarships.asia
  - name: armory.worldofwarships.asia
    url: https://armory.worldofwarships.asia
  - name: dockyard.worldofwarships.asia
    url: https://dockyard.worldofwarships.asia
    expectedStatusCodes:
      - 403
  - name: logbook.worldofwarships.asia
    url: https://logbook.worldofwarships.asia
  
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.live4.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Uptime"
  introMessage: yet another uptime page in internet. Powerred by [upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
